environment:
  matrix:
    # - PYTHON: "C:\\Python26"
    #   PYTHON_VERSION: "2.6"
    #   RUN: "%PYTHON%\\python"
    #   PIP: "%PYTHON%\\Scripts\\pip"
    #   COV: "%PYTHON%\\Scripts\\coverage"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      COV: "%PYTHON%\\Scripts\\coverage"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      COV: "%PYTHON%\\Scripts\\coverage"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      COV: "%PYTHON%\\Scripts\\coverage"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      COV: "%PYTHON%\\Scripts\\coverage"

    # - PYTHON_VERSION: "pypy2"
    #   RUN: "%APPVEYOR_BUILD_FOLDER%\\pypy-4.0.1-win32\\pypy"
    #   PIP: "%RUN% -m pip"
    #   PYPY: 'powershell.exe %APPVEYOR_BUILD_FOLDER%\\.installers\\installpypy2.ps1'
    #   COV: "%RUN% -m coverage"

    # - PYTHON_VERSION: "pypy3"
    #   RUN: "%APPVEYOR_BUILD_FOLDER%\\pypy3-2.4.0-win32\\pypy"
    #   PIP: "%RUN% -m pip"
    #   PYPY: "powershell.exe %APPVEYOR_BUILD_FOLDER%\\.installers\\installpypy3.ps1"
    #   COV: "%RUN% -m coverage"

matrix:
  allow_failures:
    - PYTHON_VERSION: "pypy2"
    - PYTHON_VERSION: "pypy3"

install:
  - "ECHO %PYTHON% %PYTHON_VERSION%%APPVEYOR_BUILD_FOLDER%"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%PYPY%"
  - "%PIP% install pytest-coverage codecov PyOpenSSL"
  - "cd %HOME%"

test: off

build_script:
  - "%RUN% -m pytest -c setup.cfg --cov=./py_src/ ./py_src/"
  - "%RUN% setup.py sdist --universal"
  - "%PIP% install --no-index --find-links=.\\dist\\ py2p"
  - "%RUN% setup.py build"
  - "FOR /F %%v IN ('%RUN% -c \"import sys, sysconfig; print(\'{}.{}-{v[0]}.{v[1]}\'.format(\'lib\', sysconfig.get_platform(), v=sys.version_info))\"') DO SET BUILD_DIR=%%v"
  - "ren .coverage .covvv"
  - "%RUN% -m pytest -c setup.cfg --cov=build\\%BUILD_DIR% build\\%BUILD_DIR%"
  - "ren .covvv .coverage.1"
  - "ren .coverage .coverage.2"

on_success:
  - "%COV% combine"
  - "%COV% xml"
  - "%RUN% -c \"import codecov; codecov.main('--token=d89f9bd9-27a3-4560-8dbb-39ee3ba020a5', '--file=coverage.xml')\""